INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(1, '2017-01-01', 'Acre', 'AC');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(2, '2017-01-01', 'Alagoas', 'AL');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(3, '2017-01-01', 'Amazonas', 'AM');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(4, '2017-01-01', 'Amapá', 'AP');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(5, '2017-01-01', 'Bahia', 'BA');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(6, '2017-01-01', 'Ceará', 'CE');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(7, '2017-01-01', 'Distrito Federal', 'DF');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(8, '2017-01-01', 'Espírito Santo', 'ES');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(9, '2017-01-01', 'Goiás', 'GO');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(10, '2017-01-01', 'Maranhão', 'MA');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(11, '2017-01-01', 'Minas Gerais', 'MG');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(12, '2017-01-01', 'Mato Grosso do Sul', 'MS');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(13, '2017-01-01', 'Mato Grosso', 'MT');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(14, '2017-01-01', 'Pará', 'PA');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(15, '2017-01-01', 'Paraíba', 'PB');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(16, '2017-01-01', 'Pernambuco', 'PE');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(17, '2017-01-01', 'Piauí', 'PI');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(18, '2017-01-01', 'Paraná', 'PR');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(19, '2017-01-01', 'Rio de Janeiro', 'RJ');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(20, '2017-01-01', 'Rio Grande do Norte', 'RN');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(21, '2017-01-01', 'Rondônia', 'RO');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(22, '2017-01-01', 'Roraima', 'RR');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(23, '2017-01-01', 'Rio Grande do Sul', 'RS');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(24, '2017-01-01', 'Santa Catarina', 'SC');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(25, '2017-01-01', 'Sergipe', 'SE');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(26, '2017-01-01', 'São Paulo', 'SP');
INSERT INTO `state`(`state_id`, `version`, `state_name`, `state_abbreviation`) VALUES(27, '2017-01-01', 'Tocantins', 'TO');